export const menus = [
  {
    menu_aid: 1,
    menu_title: "2pc Chickenjoy",
    menu_category: "Chicken Joy",
    menu_price: "199",
    menu_image: "chicken-1.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 2,
    menu_title: "3pc Chickenjoy",
    menu_category: "Chicken Joy",
    menu_price: "297",
    menu_image: "chicken-2.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 3,
    menu_title: "Family Meal 1",
    menu_category: "Chicken Joy",
    menu_price: "849",
    menu_image: "chicken-3.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 4,
    menu_title: "Family meal 2",
    menu_category: "Chicken Joy",
    menu_price: "989",
    menu_image: "chicken-4.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 5,
    menu_title: "Family meal 3",
    menu_category: "Chicken Joy",
    menu_price: "599",
    menu_image: "chicken-5.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 6,
    menu_title: "1x Bucket Chickenjoy",
    menu_category: "Chicken Joy",
    menu_price: "589",
    menu_image: "chicken-6.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 7,
    menu_title: "Value Meal 1",
    menu_category: "Value Meal",
    menu_price: "379",
    menu_image: "value-meal-1.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 8,
    menu_title: "Value Meal 2",
    menu_category: "Value Meal",
    menu_price: "189",
    menu_image: "value-meal-2.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 9,
    menu_title: "Value Meal 3",
    menu_category: "Value Meal",
    menu_price: "329",
    menu_image: "value-meal-3.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 10,
    menu_title: "Value Meal 4",
    menu_category: "Value Meal",
    menu_price: "589",
    menu_image: "value-meal-4.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 11,
    menu_title: "Value Meal 5",
    menu_category: "Value Meal",
    menu_price: "489",
    menu_image: "value-meal-5.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 12,
    menu_title: "1x  Yumburger",
    menu_category: "Burger",
    menu_price: "47",
    menu_image: "burger-1.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 13,
    menu_title: "1x  Yumburger, 1x Fries",
    menu_category: "Burger",
    menu_price: "175",
    menu_image: "burger-2.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 14,
    menu_title: "1x  Cheesy Yumburger",
    menu_category: "Burger",
    menu_price: "67",
    menu_image: "burger-3.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 15,
    menu_title: "1x Cheesy Yumburger, 1x Fries",
    menu_category: "Burger",
    menu_price: "107",
    menu_image: "burger-4.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 16,
    menu_title: "1x Cheesy Yumburger Deluxe",
    menu_category: "Burger",
    menu_price: "127",
    menu_image: "burger-5.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 17,
    menu_title: "Combo Meal 5",
    menu_category: "Burger",
    menu_price: "187",
    menu_image: "burger-6.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 18,
    menu_title: "1x Double Cheesy Yumburger Deluxe",
    menu_category: "Burger",
    menu_price: "159",
    menu_image: "burger-7.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 19,
    menu_title: "Combo Meal 1",
    menu_category: "Burger",
    menu_price: "199",
    menu_image: "burger-8.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 20,
    menu_title: "1x Peach Mango Pie",
    menu_category: "Desserts",
    menu_price: "59",
    menu_image: "dessert-1.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 21,
    menu_title: "1x Ube Pie",
    menu_category: "Desserts",
    menu_price: "69",
    menu_image: "dessert-2.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 22,
    menu_title: "2x Peach Mango Pie",
    menu_category: "Desserts",
    menu_price: "154",
    menu_image: "dessert-3.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 23,
    menu_title: "1x Pineapple Juice",
    menu_category: "Desserts",
    menu_price: "45",
    menu_image: "dessert-4.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 24,
    menu_title: "1x Pepsi",
    menu_category: "Desserts",
    menu_price: "39",
    menu_image: "dessert-5.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 25,
    menu_title: "Combo Meal 1",
    menu_category: "Burger Steak",
    menu_price: "149",
    menu_image: "steak-1.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 26,
    menu_title: "Burger Steak Platter",
    menu_category: "Burger Steak",
    menu_price: "279",
    menu_image: "steak-2.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 27,
    menu_title: "Family meal 4",
    menu_category: "Burger Steak",
    menu_price: "899",
    menu_image: "steak-3.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 28,
    menu_title: "1x Jolly Spaghetti",
    menu_category: "Spaghetti",
    menu_price: "89",
    menu_image: "spag-1.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 29,
    menu_title: "1x Jolly Spaghetti, 1x Chickenjoy",
    menu_category: "Spaghetti",
    menu_price: "189",
    menu_image: "spag-2.webp",
    menu_is_active: false,
  },
  {
    menu_aid: 30,
    menu_title: "1x Spaghetti Platter",
    menu_category: "Spaghetti",
    menu_price: "389",
    menu_image: "spag-3.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 31,
    menu_title: "1x Fries",
    menu_category: "Sides",
    menu_price: "67",
    menu_image: "sides-1.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 32,
    menu_title: "1x Mashed Potato",
    menu_category: "Sides",
    menu_price: "84",
    menu_image: "sides-2.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 33,
    menu_title: "1x Rice",
    menu_category: "Sides",
    menu_price: "48",
    menu_image: "sides-3.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 34,
    menu_title: "1x Adobo Rice",
    menu_category: "Sides",
    menu_price: "89",
    menu_image: "sides-4.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 35,
    menu_title: "1x Spaghetti Bowl",
    menu_category: "Sides",
    menu_price: "48",
    menu_image: "sides-5.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 36,
    menu_title: "1x Palabok",
    menu_category: "Palabok",
    menu_price: "99",
    menu_image: "palabok-1.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 37,
    menu_title: "1x Palabok, 1x Coke",
    menu_category: "Palabok",
    menu_price: "84",
    menu_image: "palabok-2.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 38,
    menu_title: "1x Palabok Platter",
    menu_category: "Palabok",
    menu_price: "399",
    menu_image: "palabok-3.webp",
    menu_is_active: true,
  },
  {
    menu_aid: 39,
    menu_title: "Family Meal 2",
    menu_category: "Palabok",
    menu_price: "984",
    menu_image: "palabok-4.webp",
    menu_is_active: true,
  },
];
